version: '3'

services:

    backend:
        build: ./backend
        entrypoint: ./.docker/entrypoint.sh
        volumes:
            - ./backend:/var/www
            - ./backend/.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - 8080:8000
        depends_on:
            - keycloak

    frontend:
        build: ./frontend
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/home/node/app
        ports:
            - 3000:3000
            - 35729:35729

    keycloak:
        image: quay.io/keycloak/keycloak:24.0.3
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
            - "8180:8080"
        volumes:
            - ./backend/.docker/keycloak/data:/opt/keycloak/data
        user: "1000:1000" 
        networks:
            - default

networks:
    default:
        driver: bridge
